### PR TITLE
Use OSRF ros-websocket fork

### PR DESCRIPTION
**Pull request by mvollrath**

### CODE REVIEW

**Review by jubeira — COMMENTED** [review]
Same as https://github.com/osrf/polymer-ros-rviz/pull/18#pullrequestreview-199244768, perhaps I'd wait until https://github.com/osrf/polymer-ros-websocket/pull/1 is merged and change both the fork and the version here.

**Comment by mvollrath** [comment]
As long as we tag latest 3.x we don't have to touch this.

**Comment by jubeira** [comment]
Hmm isn't the version strict with minor and patch numbers if we specify it like this?

If we make changes on `osrf/ros-websocket` and tag those changes as, for example, `3.1.0` or `3.0.1`, don't we need to change the version here to `osrf/ros-websocket#3.1.0` or `osrf/ros-websocket#3.0.1` as well to apply those changes?

**Comment by mvollrath** [comment]
[The caret makes it loose with minor versions](https://nodesource.com/blog/semver-tilde-and-caret/)

**Review by jubeira — APPROVED** [review]
Thanks for the clarification, then LGTM!

EDIT: @chapulina please feel free to merge this; I don't have write access here.

**Pull request merged**
